name: Build and deploy ASP.Net Core app to Azure Web App - dollaistore-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ĐỔI đường dẫn csproj bên dưới cho đúng với project Web API của bạn
      # (nhìn trong Solution Explorer: ví dụ WebNameProjectOfSWD/WebNameProjectOfSWD.csproj)
      - name: Restore
        run: dotnet restore ./WebNameProjectOfSWD/WebNameProjectOfSWD.csproj

      - name: Publish
        run: dotnet publish ./WebNameProjectOfSWD/WebNameProjectOfSWD.csproj -c Release -o ./publish

      # Kiểm tra có DLL JWT (bước chẩn đoán để log ra, không bắt buộc)
      - name: List publish output
        shell: pwsh
        run: |
          Get-ChildItem -Path ./publish -Recurse -Filter "System.IdentityModel.Tokens.Jwt.dll" | Format-List FullName
          Get-ChildItem -Path ./publish -Filter "*.dll" | Measure-Object

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./publish

      # (tuỳ chọn) zip lại cho chắc
      - name: Zip package
        shell: pwsh
        run: Compress-Archive -Path ./publish/* -DestinationPath ./app.zip -Force

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C34CDEA844D6447AB0A46354D33C730E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B536F8AE7264A1C8E8D60EB97852684 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9F03824DD8374956A0F9EB253480FC40 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dollaistore-api
          slot-name: Production
          package: ./app.zip   # hoặc: package: ./publish
